
services:
  ocrvision-app:
    build: .
    container_name: ocrvision-app
    volumes:
      - .:/var/www/html
    depends_on:
      - ocrvision-db
    environment:
      - DB_HOST=ocrvision-db
      - DB_PORT=3306
      - DB_DATABASE=ocrvision_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  ocrvision-db:
    image: mysql:8.0
    container_name: ocrvision-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ocrvision_db
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

  ocrvision-nginx:
    image: nginx:latest
    container_name: ocrvision-nginx
    restart: always
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ocrvision-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ocrvision-phpmyadmin
    restart: always
    depends_on:
      - ocrvision-db
    environment:
      PMA_HOST: ocrvision-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"

volumes:
  db_data:
